### ISSUE TITLE
R Studio Status 503 Error

### ISSUE THREAD

**Issue by LimaEchoAlpha** [berkeley-dsep-infra/datahub#2284] opened 2021-04-03 07:31 UTC
Hello,

The last couple of days R Studio keeps getting interrupted by a Status 503 Error very often (every 5-10 minutes or so).  The error message is similar to the Status 403 Error that happens every so often, and requires reloading to be able to keep using R.  The 403 error is annoying, but it only happens intermittently, so it is tolerable; the 503 error happens too often, though.

**Comment by felder** [comment] 2021-04-05 18:12
Typically a 403 error indicates you're attempting to access a resource the server does not believe you have the appropriate permissions to access.  A 503 error indicates the server is having an issue of some sort with satisfying your request.

It seems a little unusual to me, but not impossible, that the same issue would cause both errors.

First, have you tried accessing the hub using a browser you don't normally use?  For example, if you normally use Safari have you tried Chrome?  Additionally, have you tried disabling all browser extensions/addons while attempting to use the hub?

**Comment by LimaEchoAlpha** [comment] 2021-04-05 18:32
I've only tried accessing the hub with the browser I normally use (Chrome).  I can try using Safari and let you know if I run into the same issues.

**Comment by felder** [comment] 2021-04-05 18:52
Yeah that's where I'd start.  If it continues to occur, my next question would be about how to reproduce this issue.  If possible, if you can identify a specific set of actions that produces this issue I'd then attempt to do so using the steps you've outlined using my admin powers to connect to your server.

Additionally if you know of anyone else experiencing this, referring them to this ticket to provide input would also be helpful.

**Comment by yuvipanda** [comment] 2021-04-07 14:36
Investigating this now, with help:

I see a 404 for auth, from the hub pod:

```
[W 2021-04-07 14:07:50.442 JupyterHub log:181] 404 GET /hub/api/authorizations/token/[secret] (user@10.20.1.5) 24.60ms
```


And from the user's pod
```
[E 2021-04-07 06:28:07.004 SingleUserNotebookApp web:1789] Uncaught exception GET /user/tbay/rstudio/events/get_events (10.0.0.77)
HTTPServerRequest(protocol='https', host='r.datahub.berkeley.edu', method='GET', uri='/user/tbay/rstudio/events/get_events', version='HTTP/1.1', remote_ip='10.0.0.77')
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
result = await result
File "/opt/conda/lib/python3.8/site-packages/jupyter_server_proxy/websocket.py", line 97, in get
return await self.http_get(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 534, in http_get
return await self.proxy(self.port, path)
TypeError: object NoneType can't be used in 'await' expression
[I 2021-04-07 06:28:11.330 SingleUserNotebookApp log:181] 302 GET /user/tbay/rstudio/events/get_events -> /hub/api/oauth2/authorize?client_id=jupyterhub-user-tbay&redirect_uri=%2Fuser%2Ftbay%2Foauth_callback&response_type=code&state=[secret] (@10.0.0.25) 1.35ms
[E 2021-04-07 06:28:11.330 SingleUserNotebookApp web:1789] Uncaught exception GET /user/tbay/rstudio/events/get_events (10.0.0.25)
HTTPServerRequest(protocol='https', host='r.datahub.berkeley.edu', method='GET', uri='/user/tbay/rstudio/events/get_events', version='HTTP/1.1', remote_ip='10.0.0.25')
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
result = await result
File "/opt/conda/lib/python3.8/site-packages/jupyter_server_proxy/websocket.py", line 97, in get
return await self.http_get(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 534, in http_get
return await self.proxy(self.port, path)
TypeError: object NoneType can't be used in 'await' expression
[I 2021-04-07 06:28:42.353 SingleUserNotebookApp log:181] 200 POST /user/tbay/rstudio/events/get_events (tbay@10.0.0.77) 50070.51ms
[W 2021-04-07 07:20:04.978 SingleUserNotebookApp auth:313] No Hub user identified for request
[W 2021-04-07 07:20:04.978 SingleUserNotebookApp auth:551] Token stored in cookie may have expired
```


The hub pod is on UTC, while the user pod is on pacific, hence the time difference.

Related to https://github.com/jupyterhub/jupyterhub/issues/2299 and https://github.com/jupyterhub/jupyter-server-proxy/issues/109. I also notice that we're on jupyter-server-proxy 1.5, while latest is 3.0.2 - so am gonna bump it to see if that fixes it. The fix for the second issue there is included in 3.0.2.

**Comment by yuvipanda** [comment] 2021-04-07 17:52
I think it might not be jupyter-server-proxy version conflict alone - @petersudmant also reported this, and biology hub has a new enough version of j-s-p. It's probably still something cookie related, and I'm bumping up notebook / lab with https://github.com/berkeley-dsep-infra/datahub/pull/2291 anyway.

**Comment by yuvipanda** [comment] 2021-04-08 12:08
I've been able to reproduce it, with logs looking like this: https://gist.github.com/yuvipanda/3e7fc211278575a25b62fd770b31e8f9

**Comment by minrk** [comment] 2021-04-09 13:44
Following up, the 403 I believe is occurring hourly due to default oauth token expiry (the auth token stored in a cookie used to access anything through jupyter-server-proxy), which should be fixed by https://github.com/jupyterhub/jupyterhub/pull/3411 which changes the expiry of the token to match that of the cookie itself (default 2 weeks).

**Closed** 2021-04-12 08:36 UTC
Labels: support
