### ISSUE TITLE
Multiple Redirections Error.

### ISSUE THREAD

**Issue by rainwoodman** [berkeley-dsep-infra/datahub#42] opened 2017-08-24 04:36 UTC
When I first login to datahub from a computer it always give me a 'repeated redirection error'. I can then retry and it goes OK. 

Maybe increasing the time between retries?

**Comment by yuvipanda** [comment] 2017-09-07 00:19
Do you still experience this? I think we hunted down and fixed almost all the causes of this in the first couple weeks.

**Comment by rainwoodman** [comment] 2017-09-07 06:01
Indeed. I don't think I am seeing this any more. Thanks for the good work! 

Shall we close this issue?

**Comment by yuvipanda** [comment] 2017-09-11 21:46
Thanks! Yup, closing :)

**Closed by yuvipanda** 2017-09-11 21:46 UTC
